### ISSUE TITLE
Package not resolved on NPM

### ISSUE THREAD

**Issue by peersky** [ethers-io/ext-provider-multicall#1]
Hey! @ricmoo , wanted to say that few weeks ago I installed this package from npm but today when I was going to reinstall it for another project I found that it is gone from the registry. 
Not sure if that is done on purpose, but in any case Im looking forward to use it, thanks for your great job!

**Comment by makhnovskiy** [comment]
Same: 

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@ethers-ext%2fprovider-multicall - Not found
npm ERR! 404 
npm ERR! 404  '@ethers-ext/provider-multicall@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by xrchz** [comment]
I also had this issue. Has it been removed on purpose?

**Comment by ricmoo** [comment]
Sorry, the extension packages don't have managed deployment yet.

This has now been published. :)
