### ISSUE TITLE
Support blockTag

### ISSUE THREAD

**Issue by xrchz** [ethers-io/ext-provider-multicall#5]
Currently it looks like the multicall provider ignores the `{blockTag}` extra argument on calls. It should instead support this - and ideally throw an error if the underlying provider does not support specifying a block tag.

**Comment by ricmoo** [comment]
Completely agree. :)

I will look at it this weekend/next week.

**Comment by ricmoo** [comment]
This should now be supported.

I've tested it against Infura (for near blocks) and it works.

The contract was already set up to handle it, so it was just a matter of splitting up the requests.

This also has an added bonus:

Normally, if a node doesn't support archive access it simply ignores the blockTag and returns `"latest"`, silently providing wrong data. With this, the multi call contract includes the blockTag from the call along with the results, so the provider can check that the node honoured the blockTag parameter and will throw if the node is lying about what block the data is from.

Anyways, please try it out and let me know if it works for you and I'll publish to npm. :)
